### ISSUE TITLE
dinghy-http-proxy:2.5 won't start

### ISSUE THREAD

**Issue by dustMason** [codekitchen/dinghy-http-proxy#24]
I'm running the latest dinghy installed via homebrew. When I try either `dinghy up` or `dinghy restart`, the VM and app starts up fine, but DNS and proxy do not start. The `docker logs` for the proxy container are:

```
forego     | starting nginx.1 on port 5000
forego     | starting dockergen.1 on port 5100
forego     | starting dnsmasq.1 on port 5300
nginx.1    | 2017/01/28 23:16:39 [crit] 12#12: pread() "/etc/nginx/conf.d/custom.conf" failed (21: Is a directory)
forego     | starting nginx.1 on port 5300
forego     | sending SIGTERM to dockergen.1
forego     | sending SIGTERM to nginx.1
forego     | sending SIGTERM to dnsmasq.1
```

Dinghy has been working beautifully for me for months. I recently destroyed and recreated my VM, but had used the proxy since then for a few days.

mac OS 10.12.2
Dinghy HEAD-9328532

**Comment by codekitchen** [comment]
Looks like a problem on master with this recent PR: https://github.com/codekitchen/dinghy/pull/222

We need to check if `~/.dinghy/proxy.conf` exists before trying to mount it as a volume, otherwise docker creates it as a directory, which nginx doesn't like. I'll get a fix in before I cut the next Dinghy release.

In the meantime, you can workaround with `rmdir ~/.dinghy/proxy.conf ; touch ~/.dinghy/proxy.conf`

**Comment by codekitchen** [comment]
Fixed in https://github.com/codekitchen/dinghy/commit/149fb1497374b722a4ff64e057d078f6eef94342

**Comment by dustMason** [comment]
Thank you!
