### ISSUE TITLE
Access MySQL from the host environment directly.

### ISSUE THREAD

**Issue by jarrettj** [codekitchen/dinghy-http-proxy#45]
Hi,

Good day.

Is it possible to access a MySQL container from the host? I've tried:
0.0.0.0
192.168.99.100
localhost
app.mysql.docker

All fails, maybe there is a MySQL setting I am missing? Thanks.

Regards.
JJ

**Comment by codekitchen** [comment]
Hey @jarrettj, this isn't really related to `dinghy-http-proxy` since MySQL isn't over HTTP, it's more a general docker question. You'll need to make sure your container is configured to expose the MySQL port, and then you can access it using the VM IP or Dinghy's DNS functionality as described in https://github.com/codekitchen/dinghy#dns

**Comment by jarrettj** [comment]
Ah thanks a lot man :) That helped.
